### ISSUE TITLE
respawn time 

### ISSUE THREAD

**Issue by milivojm** [ArmA3Pro/mission-pack#16]
How long should we set it to? barracuda said 10 minutes is too long and will put off people. Consider you still need to wait for transportation to get back in the fight.

**Comment by milivojm** [comment]
@chypsa I'll set it to 7 minutes for today as you've described in the event.

**Comment by chypsa** [comment]
We didn't really agree on anything here so I just went with the middle value. We'll see how fast people get bored :)

**Comment by milivojm** [comment]
Roger that. :)

**Comment by milivojm** [comment]
Timer set, closing the issue.
