### ISSUE TITLE
Voice chat while waiting respawn

### ISSUE THREAD

**Issue by chypsa** [ArmA3Pro/mission-pack#17]
Is it possible to configure it so that people who are dead and spectating can chat to eachother, but not to others in-game?

**Comment by milivojm** [comment]
I think it's possible, isn't that the default behavior?

**Comment by chypsa** [comment]
Maybe, I couldn't remember by heart, but that's also something to look into.

**Comment by milivojm** [comment]
I think even if you can't, there is little you can do about it.

**Comment by chypsa** [comment]
TFAR feature-list says:

"Spectator mode for dead players."

**Comment by milivojm** [comment]
Don't know how it's solved in vanilla.
