### ISSUE TITLE
Isključiti VON global

### ISSUE THREAD

**Issue by chypsa** [ArmA3Pro/mission-pack#20]
Svi igrači trebaju imati pristup VON Side i VON Squad, a VON Global treba ostati ograničen na trenutno ulogiranog admina ili na specifične PID-ove, ako se može.

**Comment by milivojm** [comment]
Trenutno će ti ovo ovako funkcionirati. Ali dugoročne ćeš poželiti izbaciti i VON za side. Squad leaderi imaju posebni channel - command channel.

**Comment by chypsa** [comment]
Apsolutno, ako SL-ovi međusobno mogu komunicirati, to je dovoljno i možemo izbaciti Side.
