### ISSUE TITLE
Ugasiti Out-of-Ammo i slično urlanje / notifikacije.

### ISSUE THREAD

**Issue by chypsa** [ArmA3Pro/mission-pack#25]

**Comment by chypsa** [comment]
Jel ovo moguće riješiti sa `enablesentences false`, ali globalno, da se ne stavlja svakom pojedinačno u Init?

**Comment by milivojm** [comment]
Ako si povukao zadnju verziju sa GitHub-a jučer, to je već u init.sqf. 

https://github.com/ArmA3Pro/mission-pack/blob/alpha/A3Pro_HVT_Extraction.Altis/init.sqf

**Comment by chypsa** [comment]
Jesam, ali smo u BLUFOR-u svejedno imali dernjavu Out-of-ammo stalno. Provjerit ću danas opet.

**Comment by chypsa** [comment]
Riješeno
