### ISSUE TITLE
Srediti j**nu žicu na cesti jer još uvijek lebdi u zraku.

### ISSUE THREAD

**Issue by chypsa** [ArmA3Pro/mission-pack#27]

**Comment by milivojm** [comment]
Ako ti je ugašen disable simulation na tom objektu onda ti zato možda leti. Probaj uključiti simulation. Simulation znači da Physics engine kontrolira taj objekt i onda bi mogao pasti na pod.

**Comment by chypsa** [comment]
Riješeno
