### ISSUE TITLE
Info pano prije misije (jpg?)

### ISSUE THREAD

**Issue by chypsa** [ArmA3Pro/mission-pack#32]
Pogledati može li se elegantno dodati informativni pano prije početka misije i u kojem točno trenutku prije početka, tako da ne bude naporno starim igračima) o tome kako se pojedini mod igra i što se od igrača očekuje. Osnovne upute, VON, task itd.

**Comment by milivojm** [comment]
Ako si mislio kao loading screen - ne može se. Loading screen trpi world map i onaj mali komadić slike. Međutim - imaš briefing sekciju kod učitavanja mape. Tamo možeš sve napisati i dodati sliku, linkove na markere i sl. Pogledaj briefing moje misije.

**Comment by milivojm** [comment]
Pod dodati sliku sam mislio - dodati malu sliku koja stane u briefing. Inače se može dodati custom dialog koji može iskočiti nakon učitavanja misije ali to bi bio pain in the ass da svaki put moraš prvo proći kroz mission briefing screen pa onda na taj drugi screen pa tek onda igrati. Bolje je koristiti briefing.

**Comment by chypsa** [comment]
Dodao sam sliku i tekst u briefing.
